# code-repo/ci/tasks/build.yml
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.19-bullseye
params:
  GOARCH: amd64
  GOOS: linux
  FILE_EXTENSION: ""
inputs:
- name: version
- name: code-repo
outputs:
- name: build
platform: linux
run:
  path: /bin/sh
  args:
  - -c
  - |
    set -eux
    version="$(cat version/version)"
    cd code-repo

    # Setup dependencies
    go mod tidy

    # Build and place in the output directory.
    go build -o "../build/fetcher-${version}-${GOOS}-${GOARCH}${FILE_EXTENSION}" cmd/main.go
